CREATE TABLE (
    UserID INTEGER DEFAULT 0,
    Diamond INTEGER DEFAULT 0,
    Platinum INTEGER DEFAULT 0,
    Gold INTEGER DEFAULT 0,
    Silver INTEGER DEFAULT 0,
    Bronze INTEGER DEFAULT 0,
    PRIMARY KEY(UserID)
);